// Curated MCQ bank used by the timed assessments.
export type BankQuestion = {
  id: string;
  topic: string;
  difficulty: "easy" | "medium" | "hard";
  question: string;
  options: string[];
  correct_option: number;
  explanation: string;
};

export const ASSESSMENT_BANK: BankQuestion[] = [
  {"id": "q1", "topic": "Java", "difficulty": "easy", "question": "Which keyword is used to prevent a variable from being modified in Java?", "options": ["static", "final", "abstract", "volatile"], "correct_option": 1, "explanation": "The 'final' keyword prevents a variable's value from being changed once it is initialized."},
  {"id": "q2", "topic": "Java", "difficulty": "medium", "question": "What is the purpose of the 'super' keyword in Java?", "options": ["To call a static method", "To refer to the immediate parent class object", "To access private members of a class", "To terminate a loop"], "correct_option": 1, "explanation": "The 'super' keyword is used to refer to parent class variables, methods, or constructors."},
  {"id": "q3", "topic": "Java", "difficulty": "hard", "question": "Which of these is not a feature of Java's Garbage Collection?", "options": ["Mark and Sweep", "Stop-the-world events", "Manual memory deallocation using delete", "Generational collection"], "correct_option": 2, "explanation": "Java manages memory automatically and does not support the manual 'delete' keyword like C++."},
  {"id": "q4", "topic": "Java", "difficulty": "easy", "question": "What is the default value of a local variable in Java?", "options": ["0", "null", "No default value", "false"], "correct_option": 2, "explanation": "Local variables in Java must be initialized before use as they do not have default values."},
  {"id": "q5", "topic": "Java", "difficulty": "medium", "question": "Which interface does not allow duplicate elements?", "options": ["List", "Set", "Map", "Queue"], "correct_option": 1, "explanation": "The Set interface is designed to store unique elements and prohibits duplicates."},
  {"id": "q6", "topic": "Java", "difficulty": "easy", "question": "Which of the following is used to handle exceptions in Java?", "options": ["try-catch", "if-else", "for-each", "do-while"], "correct_option": 0, "explanation": "The try-catch block is the standard mechanism for handling runtime exceptions in Java."},
  {"id": "q7", "topic": "Java", "difficulty": "medium", "question": "What is 'Type Erasure' in Java?", "options": ["Deleting unused variables", "Converting primitive types to objects", "Removing generic type information at compile time", "Dynamic method dispatch"], "correct_option": 2, "explanation": "Type Erasure ensures that no new classes are created for parameterized types, maintaining backward compatibility."},
  {"id": "q8", "topic": "Java", "difficulty": "hard", "question": "Which memory area in JVM is shared among all threads?", "options": ["Stack", "Program Counter Register", "Heap", "Native Method Stack"], "correct_option": 2, "explanation": "The Heap and Method Area are shared across all threads, while stacks are thread-local."},
  {"id": "q9", "topic": "Java", "difficulty": "easy", "question": "Which access modifier allows access within the same package and subclasses?", "options": ["private", "public", "protected", "default"], "correct_option": 2, "explanation": "The protected modifier grants access to members within the package and to subclasses in different packages."},
  {"id": "q10", "topic": "Java", "difficulty": "medium", "question": "Can a constructor be declared 'final'?", "options": ["Yes", "No", "Only if it is private", "Only in abstract classes"], "correct_option": 1, "explanation": "Constructors cannot be final because they are not inherited by subclasses and thus cannot be overridden."},
  {"id": "q11", "topic": "Python", "difficulty": "easy", "question": "Which of these is an immutable data type in Python?", "options": ["List", "Dictionary", "Set", "Tuple"], "correct_option": 3, "explanation": "Tuples are immutable sequences whose elements cannot be changed after creation."},
  {"id": "q12", "topic": "Python", "difficulty": "medium", "question": "How is memory managed in Python?", "options": ["Manual garbage collection", "Automatic reference counting and cyclic GC", "Using pointers", "Stack allocation only"], "correct_option": 1, "explanation": "Python uses a combination of reference counting and a cyclic garbage collector to manage memory."},
  {"id": "q13", "topic": "Python", "difficulty": "hard", "question": "What is the purpose of the '__init__' method?", "options": ["To destroy an object", "To initialize a new object's attributes", "To import a module", "To define a private variable"], "correct_option": 1, "explanation": "The __init__ method acts as a constructor that is called when an object is instantiated."},
  {"id": "q14", "topic": "Python", "difficulty": "easy", "question": "What is the output of 'print(2 ** 3)'?", "options": ["6", "8", "9", "5"], "correct_option": 1, "explanation": "The ** operator is used for exponentiation, so 2 raised to the power of 3 is 8."},
  {"id": "q15", "topic": "Python", "difficulty": "medium", "question": "Which of the following creates a shallow copy of a list 'L'?", "options": ["L.copy()", "list(L)", "L[:]", "All of the above"], "correct_option": 3, "explanation": "All listed methods create a new list object containing references to the same elements as the original."},
  {"id": "q16", "topic": "Python", "difficulty": "easy", "question": "Which keyword is used for defining a function in Python?", "options": ["func", "def", "function", "define"], "correct_option": 1, "explanation": "The 'def' keyword is the standard syntax for starting a function definition."},
  {"id": "q17", "topic": "Python", "difficulty": "medium", "question": "What does the 'self' parameter represent in a class method?", "options": ["The class itself", "The current instance of the class", "A global variable", "A reserved keyword for inheritance"], "correct_option": 1, "explanation": "The self parameter provides a reference to the specific object instance being acted upon."},
  {"id": "q18", "topic": "Python", "difficulty": "hard", "question": "What is a 'decorator' in Python?", "options": ["A way to add styles to code", "A function that modifies the behavior of another function", "A specific type of list comprehension", "A tool for documentation"], "correct_option": 1, "explanation": "Decorators wrap another function to extend its behavior without permanently modifying the source code."},
  {"id": "q19", "topic": "Python", "difficulty": "easy", "question": "Which function is used to get the length of a string?", "options": ["length()", "size()", "len()", "count()"], "correct_option": 2, "explanation": "The len() function returns the number of items in an object or characters in a string."},
  {"id": "q20", "topic": "Python", "difficulty": "medium", "question": "What is the result of 'bool([])' in Python?", "options": ["True", "False", "None", "Error"], "correct_option": 1, "explanation": "Empty sequences like lists, tuples, or strings evaluate to False in a boolean context."},
  {"id": "q21", "topic": "SQL", "difficulty": "easy", "question": "Which SQL clause is used to filter records?", "options": ["WHERE", "ORDER BY", "GROUP BY", "SELECT"], "correct_option": 0, "explanation": "The WHERE clause is used to extract only those records that fulfill a specified condition."},
  {"id": "q22", "topic": "SQL", "difficulty": "medium", "question": "What is the difference between TRUNCATE and DELETE?", "options": ["TRUNCATE is a DML command", "DELETE is faster", "TRUNCATE resets identity columns", "DELETE cannot be rolled back"], "correct_option": 2, "explanation": "TRUNCATE is a DDL command that removes all rows and resets the auto-increment seed."},
  {"id": "q23", "topic": "SQL", "difficulty": "hard", "question": "Which join returns all records when there is a match in either left or right table?", "options": ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"], "correct_option": 3, "explanation": "FULL OUTER JOIN combines the results of both LEFT and RIGHT joins, returning all records."},
  {"id": "q24", "topic": "SQL", "difficulty": "easy", "question": "Which keyword is used to remove duplicate rows from a result set?", "options": ["UNIQUE", "DISTINCT", "DIFFERENT", "SINGLE"], "correct_option": 1, "explanation": "The DISTINCT keyword is placed after SELECT to eliminate duplicate rows from the output."},
  {"id": "q25", "topic": "SQL", "difficulty": "medium", "question": "What does the HAVING clause do?", "options": ["Filters rows before grouping", "Filters groups based on aggregate values", "Sorts the data", "Joins two tables"], "correct_option": 1, "explanation": "HAVING is used to apply conditions to the groups created by the GROUP BY clause."},
  {"id": "q26", "topic": "SQL", "difficulty": "easy", "question": "Which command is used to add a new column to a table?", "options": ["UPDATE TABLE", "MODIFY TABLE", "ALTER TABLE", "INSERT INTO"], "correct_option": 2, "explanation": "The ALTER TABLE command is used to add, delete, or modify columns in an existing table."},
  {"id": "q27", "topic": "SQL", "difficulty": "medium", "question": "What is a 'Primary Key'?", "options": ["A key that can be null", "A unique identifier for a row", "A key that links two tables", "A temporary key"], "correct_option": 1, "explanation": "A primary key uniquely identifies each record in a table and cannot contain NULL values."},
  {"id": "q28", "topic": "SQL", "difficulty": "hard", "question": "What is a Correlated Subquery?", "options": ["A query that runs independently", "A query that uses values from the outer query", "A query that returns only one value", "A query used in the FROM clause"], "correct_option": 1, "explanation": "Correlated subqueries depend on the outer query for their values and execute once for every row processed by the outer query."},
  {"id": "q29", "topic": "SQL", "difficulty": "easy", "question": "Which SQL operator is used to search for a specified pattern in a column?", "options": ["IN", "BETWEEN", "LIKE", "EXISTS"], "correct_option": 2, "explanation": "The LIKE operator is used in a WHERE clause to search for patterns using wildcards."},
  {"id": "q30", "topic": "SQL", "difficulty": "medium", "question": "What is the purpose of the 'UNION' operator?", "options": ["To join two tables horizontally", "To combine result sets of two SELECT statements", "To find common records", "To update multiple tables"], "correct_option": 1, "explanation": "UNION combines the result-set of two or more SELECT statements, removing duplicates by default."},
  {"id": "q31", "topic": "DBMS", "difficulty": "easy", "question": "What does 'ACID' stand for in DBMS?", "options": ["Atomicity, Consistency, Isolation, Durability", "Accuracy, Control, Integration, Data", "Access, Control, Internal, Database", "Action, Commit, Identity, Data"], "correct_option": 0, "explanation": "ACID properties ensure that database transactions are processed reliably."},
  {"id": "q32", "topic": "DBMS", "difficulty": "medium", "question": "Which normal form deals with removing partial functional dependencies?", "options": ["1NF", "2NF", "3NF", "BCNF"], "correct_option": 1, "explanation": "A table is in 2NF if it is in 1NF and no non-prime attribute is dependent on a subset of any candidate key."},
  {"id": "q33", "topic": "DBMS", "difficulty": "hard", "question": "What is a 'Phantom Read' in transaction isolation?", "options": ["Reading data that is not yet committed", "Reading same row twice and getting different values", "New rows appearing in a result set when a query is repeated", "Failure to read a locked row"], "correct_option": 2, "explanation": "Phantom reads occur when a transaction re-executes a query and finds new rows inserted by another committed transaction."},
  {"id": "q34", "topic": "DBMS", "difficulty": "easy", "question": "What is a 'Foreign Key'?", "options": ["A key that is not used", "A field that points to a Primary Key in another table", "A key used for encryption", "The main key of a table"], "correct_option": 1, "explanation": "Foreign keys establish relationships between tables by referencing the primary key of another table."},
  {"id": "q35", "topic": "DBMS", "difficulty": "medium", "question": "Which of these is a 'noSQL' database?", "options": ["MySQL", "PostgreSQL", "MongoDB", "Oracle"], "correct_option": 2, "explanation": "MongoDB is a document-oriented database classified as NoSQL because it does not use tabular relations."},
  {"id": "q36", "topic": "DBMS", "difficulty": "easy", "question": "What is the purpose of a Database Index?", "options": ["To encrypt data", "To speed up data retrieval", "To save storage space", "To prevent data duplication"], "correct_option": 1, "explanation": "Indexes are used to quickly locate data without having to search every row in a database table."},
  {"id": "q37", "topic": "DBMS", "difficulty": "medium", "question": "In an E-R diagram, what does an 'Oval' represent?", "options": ["Entity", "Relationship", "Attribute", "Key"], "correct_option": 2, "explanation": "In Entity-Relationship modeling, ovals are used to denote the attributes or properties of entities."},
  {"id": "q38", "topic": "DBMS", "difficulty": "hard", "question": "What is two-phase locking (2PL)?", "options": ["A method for database backup", "A concurrency control protocol", "A type of hashing", "A way to join tables"], "correct_option": 1, "explanation": "2PL ensures serializability by requiring that all locks are acquired before any are released."},
  {"id": "q39", "topic": "DBMS", "difficulty": "easy", "question": "Which operation is used to combine two relations based on a common attribute?", "options": ["Projection", "Selection", "Join", "Union"], "correct_option": 2, "explanation": "A Join operation combines rows from two or more tables based on a related column between them."},
  {"id": "q40", "topic": "DBMS", "difficulty": "medium", "question": "What is Data Redundancy?", "options": ["Securing the data", "Duplication of data in multiple places", "Loss of data", "Formatting the data"], "correct_option": 1, "explanation": "Data redundancy occurs when the same piece of data is stored unnecessarily in two or more separate places."},
  {"id": "q41", "topic": "Operating Systems", "difficulty": "easy", "question": "What is the core of an Operating System called?", "options": ["Shell", "Kernel", "Process", "System Call"], "correct_option": 1, "explanation": "The kernel is the central component of an OS that manages system resources and hardware communication."},
  {"id": "q42", "topic": "Operating Systems", "difficulty": "medium", "question": "What is 'Thrashing' in OS?", "options": ["A high rate of page faults", "Excessive CPU usage", "Disk failure", "Slow network speed"], "correct_option": 0, "explanation": "Thrashing occurs when the system spends more time swapping pages in and out of memory than executing processes."},
  {"id": "q43", "topic": "Operating Systems", "difficulty": "hard", "question": "Which algorithm is used to prevent Deadlocks?", "options": ["Round Robin", "Banker's Algorithm", "FIFO", "LRU"], "correct_option": 1, "explanation": "Banker's algorithm tests for safety by simulating the allocation for predetermined maximum possible amounts of all resources."},
  {"id": "q44", "topic": "Operating Systems", "difficulty": "easy", "question": "What is a 'Process'?", "options": ["A program in execution", "A program in storage", "A part of the hardware", "A user interface"], "correct_option": 0, "explanation": "A process is an active entity representing a program that is currently being executed by the CPU."},
  {"id": "q45", "topic": "Operating Systems", "difficulty": "medium", "question": "What is 'Virtual Memory'?", "options": ["Physical RAM", "Hard disk space used as RAM", "A type of cache", "Read-only memory"], "correct_option": 1, "explanation": "Virtual memory allows the execution of processes that are not completely in main memory by using disk space."},
  {"id": "q46", "topic": "Operating Systems", "difficulty": "easy", "question": "Which of these is a CPU scheduling algorithm?", "options": ["TCP", "Round Robin", "HTTP", "B-Tree"], "correct_option": 1, "explanation": "Round Robin is a preemptive scheduling algorithm that assigns a fixed time slice to each process."},
  {"id": "q47", "topic": "Operating Systems", "difficulty": "medium", "question": "What is a Semaphore?", "options": ["A hardware component", "An integer variable used for process synchronization", "A type of interrupt", "A file system"], "correct_option": 1, "explanation": "Semaphores are synchronization tools used to manage access to shared resources in a multi-processing environment."},
  {"id": "q48", "topic": "Operating Systems", "difficulty": "hard", "question": "What is 'Belady's Anomaly'?", "options": ["CPU speed decreasing", "Page fault rate increasing with more frames", "Deadlock occurrence", "Fragmentation in disk"], "correct_option": 1, "explanation": "Belady's Anomaly is a phenomenon where increasing the number of page frames results in an increase in the number of page faults for certain algorithms like FIFO."},
  {"id": "q49", "topic": "Operating Systems", "difficulty": "easy", "question": "What is the purpose of a Bootloader?", "options": ["To shut down the PC", "To load the OS into memory", "To run applications", "To scan for viruses"], "correct_option": 1, "explanation": "A bootloader is a small program that starts the operating system after the computer is powered on."},
  {"id": "q50", "topic": "Operating Systems", "difficulty": "medium", "question": "What is a 'Context Switch'?", "options": ["Changing a user", "Saving state of one process and loading another", "Switching between hard drives", "Formatting a partition"], "correct_option": 1, "explanation": "Context switching is the process of storing the state of a CPU so that it can be restored and execution resumed from the same point later."},
  {"id": "q51", "topic": "Computer Networks", "difficulty": "easy", "question": "Which layer of the OSI model is responsible for routing?", "options": ["Physical", "Data Link", "Network", "Transport"], "correct_option": 2, "explanation": "The Network layer handles logical addressing and determines the best physical path for data to travel."},
  {"id": "q52", "topic": "Computer Networks", "difficulty": "medium", "question": "What is the purpose of ARP (Address Resolution Protocol)?", "options": ["Map IP to MAC address", "Map Domain to IP", "Secure the connection", "Error reporting"], "correct_option": 0, "explanation": "ARP is used to find the hardware (MAC) address of a host when its IP address is known."},
  {"id": "q53", "topic": "Computer Networks", "difficulty": "hard", "question": "Which TCP mechanism is used to control data flow?", "options": ["Checkback", "Sliding Window", "Handshake", "Hop count"], "correct_option": 1, "explanation": "The sliding window protocol is used by TCP to manage the flow of data packets between sender and receiver."},
  {"id": "q54", "topic": "Computer Networks", "difficulty": "easy", "question": "What does HTTP stand for?", "options": ["HyperText Transfer Protocol", "HighTech Transmission Process", "Hyperlink Transfer Path", "HyperText Total Protocol"], "correct_option": 0, "explanation": "HTTP is the foundation of data communication for the World Wide Web."},
  {"id": "q55", "topic": "Computer Networks", "difficulty": "medium", "question": "Which protocol is connectionless?", "options": ["TCP", "FTP", "UDP", "SSH"], "correct_option": 2, "explanation": "UDP is a connectionless protocol that sends data without establishing a formal connection or guaranteeing delivery."},
  {"id": "q56", "topic": "Computer Networks", "difficulty": "easy", "question": "What is the range of a Class C IP address?", "options": ["1-126", "128-191", "192-223", "224-239"], "correct_option": 2, "explanation": "Class C IP addresses begin with a first octet range of 192 to 223."},
  {"id": "q57", "topic": "Computer Networks", "difficulty": "medium", "question": "What is the function of a 'Gateway'?", "options": ["Amplifying signals", "Connecting two different networks", "Assigning IP addresses", "Filtering MAC addresses"], "correct_option": 1, "explanation": "A gateway acts as a 'gate' between two networks that may use different protocols."},
  {"id": "q58", "topic": "Computer Networks", "difficulty": "hard", "question": "Which of these is a Link State routing protocol?", "options": ["RIP", "BGP", "OSPF", "EGP"], "correct_option": 2, "explanation": "OSPF (Open Shortest Path First) is a link-state routing protocol that uses Dijkstra's algorithm."},
  {"id": "q59", "topic": "Computer Networks", "difficulty": "easy", "question": "What is the port number for HTTPS?", "options": ["80", "21", "443", "25"], "correct_option": 2, "explanation": "HTTPS (Secure) defaults to port 443, while standard HTTP uses port 80."},
  {"id": "q60", "topic": "Computer Networks", "difficulty": "medium", "question": "What does DNS do?", "options": ["Encrypts web traffic", "Translates domain names to IP addresses", "Routes packets", "Allocates bandwidth"], "correct_option": 1, "explanation": "DNS acts like a phonebook for the internet, converting human-readable names like google.com to IP addresses."},
  {"id": "q61", "topic": "Data Structures", "difficulty": "easy", "question": "Which data structure uses the LIFO principle?", "options": ["Queue", "Stack", "Linked List", "Tree"], "correct_option": 1, "explanation": "A Stack follows the Last-In-First-Out principle where the last element added is the first one removed."},
  {"id": "q62", "topic": "Data Structures", "difficulty": "medium", "question": "What is the time complexity of searching in a Binary Search Tree (average case)?", "options": ["O(1)", "O(n)", "O(log n)", "O(n log n)"], "correct_option": 2, "explanation": "In a balanced BST, each comparison eliminates half of the remaining nodes, resulting in logarithmic time complexity."},
  {"id": "q63", "topic": "Data Structures", "difficulty": "hard", "question": "What is the worst-case time complexity of QuickSort?", "options": ["O(n log n)", "O(n^2)", "O(n)", "O(log n)"], "correct_option": 1, "explanation": "QuickSort becomes O(n^2) when the pivot is consistently the smallest or largest element, leading to unbalanced partitions."},
  {"id": "q64", "topic": "Data Structures", "difficulty": "easy", "question": "What is a 'Linear' data structure?", "options": ["Tree", "Graph", "Array", "Heap"], "correct_option": 2, "explanation": "An array is a linear data structure because its elements are stored in contiguous memory locations and accessed sequentially."},
  {"id": "q65", "topic": "Data Structures", "difficulty": "medium", "question": "Which data structure is best for implementing a BFS traversal on a graph?", "options": ["Stack", "Queue", "Priority Queue", "Hash Map"], "correct_option": 1, "explanation": "Breadth-First Search uses a Queue to keep track of discovered but unvisited nodes in the correct order."},
  {"id": "q66", "topic": "Data Structures", "difficulty": "easy", "question": "What is the main advantage of a Linked List over an Array?", "options": ["Random access", "Dynamic size", "Less memory usage", "Faster sorting"], "correct_option": 1, "explanation": "Linked lists can grow or shrink in size during execution without needing to reallocate the entire structure."},
  {"id": "q67", "topic": "Data Structures", "difficulty": "medium", "question": "In a Max-Heap, where is the largest element located?", "options": ["Leaf node", "Middle node", "Root node", "Random node"], "correct_option": 2, "explanation": "By definition, a Max-Heap maintains the largest element at the root of the tree."},
  {"id": "q68", "topic": "Data Structures", "difficulty": "hard", "question": "What is a 'Hash Collision'?", "options": ["A key being deleted", "Two different keys producing the same hash value", "Memory overflow", "Incorrect hash function syntax"], "correct_option": 1, "explanation": "Collision occurs when a hash function maps two distinct inputs to the same array index."},
  {"id": "q69", "topic": "Data Structures", "difficulty": "easy", "question": "Which sorting algorithm is known as 'Divide and Conquer'?", "options": ["Bubble Sort", "Insertion Sort", "Merge Sort", "Selection Sort"], "correct_option": 2, "explanation": "Merge Sort recursively divides the array into halves, sorts them, and then merges them back together."},
  {"id": "q70", "topic": "Data Structures", "difficulty": "medium", "question": "What is a 'Circular Linked List'?", "options": ["A list with no nodes", "A list where the last node points to the first node", "A list that stores circles", "A doubly linked list"], "correct_option": 1, "explanation": "A circular linked list is a variation where the next pointer of the last node is not null but points back to the head."},
  {"id": "q71", "topic": "React", "difficulty": "easy", "question": "What is JSX?", "options": ["A JavaScript library", "A syntax extension for JavaScript", "A CSS framework", "A database"], "correct_option": 1, "explanation": "JSX allows you to write HTML-like code inside a JavaScript file for React components."},
  {"id": "q72", "topic": "React", "difficulty": "medium", "question": "What is the purpose of 'useEffect' hook?", "options": ["To store state", "To perform side effects", "To speed up rendering", "To navigate between pages"], "correct_option": 1, "explanation": "The useEffect hook is used for data fetching, subscriptions, or manually changing the DOM in functional components."},
  {"id": "q73", "topic": "React", "difficulty": "hard", "question": "What is the 'Virtual DOM'?", "options": ["A direct copy of the browser DOM", "A lightweight representation of the real DOM in memory", "A server-side database", "A CSS styling tool"], "correct_option": 1, "explanation": "React uses the Virtual DOM to calculate the most efficient way to update the actual browser UI."},
  {"id": "q74", "topic": "React", "difficulty": "easy", "question": "How do you pass data from a parent to a child component?", "options": ["Using State", "Using Props", "Using Context", "Using Redux"], "correct_option": 1, "explanation": "Props (properties) are the standard way to pass read-only data from a parent component down to its children."},
  {"id": "q75", "topic": "React", "difficulty": "medium", "question": "What is the 'Key' prop used for in lists?", "options": ["To identify elements uniquely for reconciliation", "To style items", "To store data", "To handle clicks"], "correct_option": 0, "explanation": "Keys help React identify which items have changed, been added, or removed, optimizing rendering performance."},
  {"id": "q76", "topic": "React", "difficulty": "hard", "question": "What does 'Lifting State Up' mean?", "options": ["Moving state to a global store", "Moving state to a common ancestor of components that need it", "Deleting the state", "Improving performance"], "correct_option": 1, "explanation": "Lifting state up involves moving shared state to the closest common parent so multiple child components can stay in sync."},
  {"id": "q77", "topic": "Node.js", "difficulty": "easy", "question": "What is Node.js?", "options": ["A programming language", "A JavaScript runtime built on V8", "A frontend framework", "A database engine"], "correct_option": 1, "explanation": "Node.js is an open-source environment that allows JavaScript to be executed on the server side."},
  {"id": "q78", "topic": "Node.js", "difficulty": "medium", "question": "Which module is used to create a web server in Node.js?", "options": ["fs", "path", "http", "os"], "correct_option": 2, "explanation": "The built-in 'http' module provides the functionality to create a server and handle requests/responses."},
  {"id": "q79", "topic": "Node.js", "difficulty": "hard", "question": "What is the 'Event Loop' in Node.js?", "options": ["A tool for UI design", "A mechanism that handles non-blocking I/O operations", "A way to loop through arrays", "A security feature"], "correct_option": 1, "explanation": "The event loop allows Node.js to perform non-blocking I/O operations by offloading tasks to the system kernel whenever possible."},
  {"id": "q80", "topic": "Node.js", "difficulty": "easy", "question": "What does 'npm' stand for?", "options": ["Node Project Manager", "Node Package Manager", "New Project Module", "Node Power Mode"], "correct_option": 1, "explanation": "npm is the default package manager for Node.js, used to install and manage third-party libraries."},
  {"id": "q81", "topic": "Node.js", "difficulty": "medium", "question": "Which function is used to include modules in Node.js?", "options": ["import", "include", "require", "attach"], "correct_option": 2, "explanation": "The 'require' function is the CommonJS way to import modules and local files in Node.js."},
  {"id": "q82", "topic": "Node.js", "difficulty": "hard", "question": "What is the purpose of 'module.exports'?", "options": ["To import a package", "To expose functions or objects for use in other files", "To delete a module", "To compile code"], "correct_option": 1, "explanation": "module.exports is an object used to define what a module exports so it can be required in other files."},
];

export const ASSESSMENTS = [
  { id: "java", title: "Java Assessment", topics: ["Java"], minutes: 15 },
  { id: "python", title: "Python Assessment", topics: ["Python"], minutes: 15 },
  { id: "sql", title: "SQL Assessment", topics: ["SQL"], minutes: 15 },
  { id: "dbms", title: "DBMS Assessment", topics: ["DBMS"], minutes: 15 },
  { id: "os", title: "Operating Systems Assessment", topics: ["Operating Systems"], minutes: 15 },
  { id: "cn", title: "Computer Networks Assessment", topics: ["Computer Networks"], minutes: 15 },
  { id: "dsa", title: "DSA Assessment", topics: ["Data Structures"], minutes: 20 },
  {
    id: "fullstack",
    title: "Full Stack Assessment",
    topics: ["React", "Node.js", "SQL", "Java"],
    minutes: 25,
  },
  {
    id: "mixed",
    title: "Mixed Technical Assessment",
    topics: [
      "Java",
      "Python",
      "SQL",
      "DBMS",
      "Operating Systems",
      "Computer Networks",
      "Data Structures",
      "React",
      "Node.js",
    ],
    minutes: 30,
  },
] as const;

export type AssessmentDef = (typeof ASSESSMENTS)[number];

export function buildAssessment(def: AssessmentDef, limit = 20): BankQuestion[] {
  const pool = ASSESSMENT_BANK.filter((q) => (def.topics as readonly string[]).includes(q.topic));
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.max(10, Math.min(limit, shuffled.length)));
}
