/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated/assessments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMockInterviewRouteImport } from './routes/_authenticated/mock-interview'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedQuestionBankRouteImport } from './routes/_authenticated/question-bank'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMockInterviewRoute =
  AuthenticatedMockInterviewRouteImport.update({
    id: '/mock-interview',
    path: '/mock-interview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestionBankRoute =
  AuthenticatedQuestionBankRouteImport.update({
    id: '/question-bank',
    path: '/question-bank',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mock-interview': typeof AuthenticatedMockInterviewRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/question-bank': typeof AuthenticatedQuestionBankRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mock-interview': typeof AuthenticatedMockInterviewRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/question-bank': typeof AuthenticatedQuestionBankRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/mock-interview': typeof AuthenticatedMockInterviewRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/question-bank': typeof AuthenticatedQuestionBankRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assessments'
    | '/dashboard'
    | '/mock-interview'
    | '/practice'
    | '/progress'
    | '/question-bank'
    | '/roadmap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/assessments'
    | '/dashboard'
    | '/mock-interview'
    | '/practice'
    | '/progress'
    | '/question-bank'
    | '/roadmap'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assessments'
    | '/_authenticated/dashboard'
    | '/_authenticated/mock-interview'
    | '/_authenticated/practice'
    | '/_authenticated/progress'
    | '/_authenticated/question-bank'
    | '/_authenticated/roadmap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mock-interview': {
      id: '/_authenticated/mock-interview'
      path: '/mock-interview'
      fullPath: '/mock-interview'
      preLoaderRoute: typeof AuthenticatedMockInterviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/question-bank': {
      id: '/_authenticated/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof AuthenticatedQuestionBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMockInterviewRoute: typeof AuthenticatedMockInterviewRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedQuestionBankRoute: typeof AuthenticatedQuestionBankRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMockInterviewRoute: AuthenticatedMockInterviewRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedQuestionBankRoute: AuthenticatedQuestionBankRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
