ALTER TABLE public.questions ADD COLUMN IF NOT EXISTS question_type text NOT NULL DEFAULT 'conceptual';

UPDATE public.questions SET question_type = CASE
  WHEN options IS NOT NULL THEN 'mcq'
  WHEN category = 'hr' THEN 'interview'
  ELSE 'conceptual' END;

INSERT INTO public.questions (category, topic, difficulty, question, model_answer, options, correct_option, question_type) VALUES
('mcq','Java','easy','Which of these is NOT a primitive type in Java?','String is a class, not a primitive type. Java has 8 primitives: byte, short, int, long, float, double, char, boolean.','["int","String","char","boolean"]'::jsonb,1,'mcq'),
('mcq','Java','medium','What is the time complexity of HashMap.get() in the average case?','Hashing gives O(1) average lookup; worst case degrades to O(log n) in modern Java due to treeified bins.','["O(n)","O(log n)","O(1)","O(n log n)"]'::jsonb,2,'mcq'),
('technical','Java','medium','Explain the difference between ArrayList and LinkedList in Java.','ArrayList uses a dynamic array: O(1) random access, costly mid-list inserts. LinkedList uses a doubly linked list: O(1) insert/delete when you hold the node, but O(n) access. Use ArrayList by default; LinkedList only for heavy front/mid mutation.',NULL,NULL,'conceptual'),
('technical','Java','medium','What is the Java Collections Framework? Describe List, Set and Map.','It is a unified set of interfaces and implementations for groups of objects. List is an ordered collection allowing duplicates (ArrayList, LinkedList). Set forbids duplicates (HashSet, TreeSet, LinkedHashSet). Map stores key to value pairs with unique keys (HashMap, TreeMap, LinkedHashMap).',NULL,NULL,'conceptual'),
('technical','Java','easy','Write a Java method that reverses a string without using StringBuilder.reverse().','public static String reverse(String s){ char[] c = s.toCharArray(); int i=0, j=c.length-1; while(i<j){ char t=c[i]; c[i++]=c[j]; c[j--]=t; } return new String(c); } Time O(n), space O(n).',NULL,NULL,'coding'),
('mcq','Python','easy','Which Python data structure is immutable?','Tuples are immutable; lists, sets and dicts are mutable.','["list","dict","tuple","set"]'::jsonb,2,'mcq'),
('technical','Python','medium','What are Python decorators and when would you use them?','A decorator is a callable that takes a function and returns a wrapped function, applied with @syntax. Used for cross-cutting concerns: logging, caching (functools.lru_cache), timing, authentication and validation, without editing the wrapped function.',NULL,NULL,'conceptual'),
('technical','Python','easy','Write a Python function that returns the first non-repeating character in a string.','from collections import Counter\ndef first_unique(s):\n    counts = Counter(s)\n    for ch in s:\n        if counts[ch] == 1:\n            return ch\n    return None\nTime O(n), space O(k).',NULL,NULL,'coding'),
('mcq','C','easy','What does the sizeof operator return in C?','sizeof returns the size in bytes of a type or object, evaluated at compile time.','["Number of elements","Size in bytes","Address of variable","Number of bits"]'::jsonb,1,'mcq'),
('technical','C','medium','Explain the difference between malloc and calloc in C.','malloc(n) allocates n bytes of uninitialised memory. calloc(count, size) allocates count*size bytes and zero-initialises them. Both return void* and must be freed with free(); always check for NULL.',NULL,NULL,'conceptual'),
('technical','C','medium','What is a dangling pointer and how do you avoid it?','A dangling pointer points to memory that has been freed or gone out of scope. Dereferencing it is undefined behaviour. Avoid it by setting pointers to NULL after free, not returning addresses of local variables, and keeping clear ownership of allocations.',NULL,NULL,'conceptual'),
('mcq','DSA','medium','Which algorithm technique does the 0/1 Knapsack problem classically use?','It has overlapping subproblems and optimal substructure, so dynamic programming gives the optimal solution; greedy fails for 0/1.','["Greedy","Dynamic Programming","Divide and Conquer","Backtracking only"]'::jsonb,1,'mcq'),
('technical','DSA','hard','Explain dynamic programming and identify when a problem is a DP candidate.','DP solves problems with optimal substructure and overlapping subproblems by storing subproblem results (memoisation top-down or tabulation bottom-up). Signals: counting ways, min/max over choices, sequences with constraints. Examples: LIS, edit distance, knapsack, coin change.',NULL,NULL,'conceptual'),
('technical','DSA','medium','Write a function to detect a cycle in a linked list.','Use Floyd''s tortoise and hare: advance slow by one and fast by two; if they meet there is a cycle, if fast hits null there is none. Time O(n), space O(1).',NULL,NULL,'coding'),
('mcq','SQL','medium','Which JOIN returns all rows from the left table and matching rows from the right?','LEFT JOIN keeps every left row, filling NULLs where no right match exists.','["INNER JOIN","LEFT JOIN","RIGHT JOIN","CROSS JOIN"]'::jsonb,1,'mcq'),
('technical','SQL','medium','Explain the different types of SQL joins with an example.','INNER JOIN returns only matched rows. LEFT/RIGHT OUTER JOIN keeps all rows of one side with NULLs for non-matches. FULL OUTER JOIN keeps both sides. CROSS JOIN is the cartesian product. SELF JOIN joins a table to itself, e.g. employees to their managers.',NULL,NULL,'conceptual'),
('technical','SQL','medium','Write a SQL query to find the second highest salary from an employees table.','SELECT MAX(salary) FROM employees WHERE salary < (SELECT MAX(salary) FROM employees); or SELECT DISTINCT salary FROM employees ORDER BY salary DESC OFFSET 1 LIMIT 1;',NULL,NULL,'coding'),
('technical','DBMS','medium','What is normalisation? Explain 1NF, 2NF and 3NF.','Normalisation organises data to reduce redundancy and anomalies. 1NF: atomic values, no repeating groups. 2NF: 1NF plus no partial dependency on part of a composite key. 3NF: 2NF plus no transitive dependency of non-key attributes on the key.',NULL,NULL,'conceptual'),
('mcq','Operating Systems','medium','Which condition is NOT required for a deadlock to occur?','Deadlock requires mutual exclusion, hold and wait, no preemption and circular wait. Preemption actually breaks deadlock.','["Mutual exclusion","Hold and wait","Preemption","Circular wait"]'::jsonb,2,'mcq'),
('technical','Operating Systems','medium','Explain the difference between a process and a thread.','A process is an independent execution unit with its own address space; a thread is a lightweight unit inside a process sharing its memory and file descriptors but with its own stack and registers. Threads are cheaper to create and communicate, but need synchronisation.',NULL,NULL,'conceptual'),
('technical','Computer Networks','medium','Explain the difference between TCP and UDP.','TCP is connection-oriented, reliable, ordered, flow and congestion controlled, with higher overhead (web, email). UDP is connectionless, unreliable and unordered but low latency (video, gaming, DNS).',NULL,NULL,'conceptual'),
('mcq','Computer Networks','easy','Which layer of the OSI model does the IP protocol operate on?','IP is a network layer (layer 3) protocol responsible for logical addressing and routing.','["Transport","Network","Data Link","Session"]'::jsonb,1,'mcq'),
('technical','OOP','easy','Explain the four pillars of object oriented programming.','Encapsulation bundles data with the methods that operate on it and hides internals. Abstraction exposes only essential behaviour. Inheritance lets a class reuse and extend another. Polymorphism lets one interface act on many types via overriding and overloading.',NULL,NULL,'conceptual'),
('mcq','Machine Learning','medium','What does overfitting mean?','An overfit model learns noise in the training set: high training accuracy, poor generalisation to unseen data. Fix with regularisation, more data, or simpler models.','["Model performs poorly on training data","Model memorises training data and generalises poorly","Model has too few parameters","Model trains too slowly"]'::jsonb,1,'mcq'),
('technical','Machine Learning','medium','Explain the bias-variance tradeoff.','Bias is error from overly simple assumptions (underfitting); variance is sensitivity to training data (overfitting). Total error is bias squared plus variance plus irreducible noise. Model complexity, regularisation and more data balance the two.',NULL,NULL,'conceptual'),
('technical','React','medium','What is the virtual DOM and how does React use it?','React keeps a lightweight JS representation of the UI. On state change it renders a new tree, diffs it against the previous one (reconciliation) and applies the minimal set of real DOM mutations, which is faster and more predictable than manual DOM updates.',NULL,NULL,'conceptual'),
('mcq','React','easy','Which hook is used to perform side effects in a React function component?','useEffect runs side effects after render; useState holds state, useMemo caches values, useRef holds mutable refs.','["useState","useEffect","useMemo","useRef"]'::jsonb,1,'mcq'),
('technical','Node.js','medium','Explain the Node.js event loop.','Node runs JS on a single thread with a libuv event loop. Callbacks are processed in phases (timers, pending, poll, check, close), with microtasks (promises, process.nextTick) drained between phases. Blocking the loop with CPU-heavy sync work stalls all requests.',NULL,NULL,'conceptual'),
('mcq','Node.js','medium','Which module system does Node.js traditionally use?','Node historically uses CommonJS (require/module.exports); ES modules are supported with .mjs or type: module.','["AMD","CommonJS","UMD","SystemJS"]'::jsonb,1,'mcq'),
('hr','Behavioural','medium','Tell me about a time you failed and what you learned.','Use STAR. Pick a real, low-stakes failure, state the situation and your role, explain the concrete action you took afterwards, and end with the measurable lesson and how you have applied it since.',NULL,NULL,'interview'),
('hr','Teamwork','medium','Describe a conflict you had in a team project and how you resolved it.','Use STAR. Describe the disagreement objectively, show you listened to the other view, explain the compromise or data you used to decide, and finish with the outcome and improved working relationship.',NULL,NULL,'interview');